@startuml

    :User: as User
    :Administrateur informatique: as Admin
    :Collaborateurs ressources humaines: as RH
    :Technicien équipement: as Tech
    :Lanceur d'alerte: as Alert
    :Pompier: as Fire
    :Superviseur: as Super

    Admin --|> User
    Admin --|> RH
    Admin --|> Tech
    Admin --|> Alert
    Admin --|> Fire
    Admin --|> Super

    Super --|> Fire

    RH --|> User
    Tech --|> User
    Alert --|> User
    Fire --|> User
    Super --|> User

package Website {
    usecase "Connection au site" as UC0

    usecase "Consulter son profil utilisateur" as UC1
    usecase "Visualiser ses compétences" as UC11
    usecase "Visualiser ses formations" as UC12
    usecase "Visualiser ses certifications" as UC13
    usecase "Visualiser ses horaires" as UC14
    usecase "Gestion de son profil utilisateur" as UC15

    usecase "Consultation du profil RH" as UC2
    usecase "Acces droit connection RH" as UC2A
    usecase "Gestion de tous les profils utilisateur" as UC22
    usecase "Gestion des comptétences" as UC23
    usecase "Gestion des formations" as UC24
    usecase "Gestion des certifications" as UC25
    usecase "Affectation des horaires" as UC26
    usecase "Gestion des équipements" as UC27

    usecase "Consultation du profil pompier" as UC3
    usecase "Acces droit connection Pompier" as UC3A
    usecase "Visualiser ses équipements" as UC31
    usecase "Gestion des interventions" as UC32
    usecase "Mettre fin à une intervention" as UC33
    usecase "Gestion de l'analyse d'intervention" as UC34

    usecase "Consultation du profil technicien" as UC4
    usecase "Acces droit connection Technicien" as UC4A
    usecase "Gestion de la maintenance des équipements" as UC41

    usecase "Consultation du profil lanceur d'alerte" as UC5
    usecase "Acces droit connection Lanceur d'alerte" as UC5A
    usecase "Gestion des alertes" as UC51
    usecase "Gestion des incidents" as UC52

    usecase "Consultation profil superviseur" as UC6
    usecase "Acces droit connection Superviseur" as UC6A
    usecase "Création des équipes d'interventions" as UC61
}

    User --> UC0
    UC1 ..> UC0 : extends
    UC2 ..> UC0 : extends
    UC3 ..> UC0 : extends

    User -left-> UC1
    UC11 ..> UC1 : extends
    UC12 ..> UC1 : extends
    UC13 ..> UC1 : extends
    UC14 ..> UC1 : extends
    UC15 ..> UC1 : extends

    RH --> UC2A
    UC2 ..> UC2A : include
    UC22 ..> UC2 : extends
    UC23 ..> UC2 : extends
    UC24 ..> UC2 : extends
    UC25 ..> UC2 : extends
    UC26 ..> UC2 : extends

    Fire --> UC3A
    UC3 ..> UC3A : include
    UC31 ..> UC3 : extends
    UC32 ..> UC3 : extends
    UC34 ..> UC3 : extends
    UC32 ..> UC33 : extends
    UC33 ..> UC34 : include

    Tech --> UC4A
    UC4 ..> UC4A : include
    UC41 ..> UC4 : extends

    Alert --> UC5A
    UC5 ..> UC5A : include
    UC51 ..> UC5 : extends
    UC52 ..> UC5 : extends

    Super --> UC6A
    UC6 ..> UC6A : include
    UC61 ..> UC6 : extends
@enduml
